version: "3.8"

services:
  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_DOCKER_TAG}
    restart: always
    hostname: beacon-chain
    command: --config-file=/config/beacon.yaml
    ports:
      - ${BEACON_API_IP}:4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    networks:
      default:
        aliases:
          - prysm_beacon_slasher
    volumes:
      - ./config/prysm/slasher/beacon.yaml:/config/beacon.yaml:ro
      - ./data/prysm/beacon-slasher:/data
    <<: *logging

  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
    restart: on-failure
    hostname: validator
    depends_on:
      - beacon
    command: --config-file=/config/validator.yaml
    ports:   
      - ${BEACON_API_IP}:7500:7500/tcp # web-ui
    volumes:
      - ./config/prysm/validator.yaml:/config/validator.yaml:ro
      - ./data/prysm/validator:/data
    <<: *logging

  slasher:
    image: gcr.io/prysmaticlabs/prysm/slasher:${PRYSM_SLASHER_DOCKER_TAG}
    restart: always
    hostname: slasher
    depends_on:
      - beacon
    command: --config-file=/config/slasher.yaml
    volumes:
      - ./config/prysm/slasher/slasher.yaml:/config/slasher.yaml:ro
      - ./data/prysm/slasher:/data
    <<: *logging

# EOF